name: flickfeedpro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  ionicons: ^0.2.1
  image_picker: ^1.1.2
  video_player: ^2.2.19
  share_plus: ^10.0.0
  font_awesome_flutter: ^10.3.0
  intl: ^0.18.0
  supabase_flutter: ^1.6.1
  postgrest: ^1.5.2
  storage_client: ^1.5.4
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  timeago: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/flickfeed.png
    - assets/images/post1.jpg
    - assets/images/post2.jpg
    - assets/images/avatar1.jpg
    - assets/images/avatar2.jpg
    - assets/images/login_illustration.png
    - assets/images/Signup_illustration.png

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf